import AppProvider from "@/components/AppProvider";
import { Inter } from "next/font/google";
import "@/styles/normalize.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
